# Header
menu:
  网站首页: /
  专题系列: /categories/special/
  解决方案: /categories/works/
  工具资源: /tools/
  我的生活: /categories/life/
  关于我们: /about/
  文章标签: /tags/
  时间归档: /archives/
rss: /atom.xml

submenu:
  前端: /categories/special/front-end
  PHP: /categories/special/php

github: https://github.com/haizhilin2013

# Content
excerpt_link: '[阅读全文]'
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
