# Header
menu:
  网站首页: /index.html
  专题系列: /categories/special/index.html
  解决方案: /categories/solution/index.html
  工具资源: /tools/index.html
  我的生活: /categories/life/index.html
  关于我们: /about/index.html
  文章标签: /tags/index.html
  时间归档: /archives/index.html

sub_menu:
  special: 
    categories/php: PHP
    categories/nodejs: Nodejs
    categories/sql: 数据库
  life: 
    categories/happy: 开心一刻
    categories/tour: 旅游
  solution:
    categories/safe: 安全
    categories/performance: 性能
  tools:
    manual: 手册
    friendly: 友情链接
  tag:
    tags: 文章标签
  about: 
    about: 关于我
    works: 开源项目
    read: 我的读书
    history: 博客历史
  archives:
    all: 全部
    new: 最新
    '2017': 2017
    '2016': 2016
    '2015': 2015


# 头像
avatar: /images/logo.png

default_category: special
category_map:
    专题: special
    方案: solution
    生活: life

per_page: 3

submenu:
  前端: /categories/special/front-end
  PHP: /categories/special/php

github: https://github.com/haizhilin2013
blog_theme: https://github.com/haizlin/blog-theme

# Content
excerpt_link: '[阅读全文]'
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- ad
- tag

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
# favicon 文件要放在haizlin/source下
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:

# 要修改根目录下的配置
permalink: posts/:abbrlink/

search:
  path: search.xml
  field: all

# yarn add hexo-generator-feed --save
rss: /atom.xml
feed:
  type: atom
  path: atom.xml
  limit: 0
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '

# 站点地图
# yarn add hexo-generator-sitemap --save
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml


excerptLength: 350


